defaults: &defaults
  working_directory: ~/APP
  docker:
  - image: circleci/node:9.5.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - dependency-cache-{{ checksum "package.json" }}
        - dependency-cache-
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ~/app-name/node_modules/
    - run:
        name: install dependencies
        command: npm install
    - run:
        name: Build library
        command: npm run build 
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/APP/.npmrc
    - run:
        name: npm publish
        command: npm publish ./dist/ngx-currency-formatter

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
